# ═══════════════════════════════════════════════════════════════════════════════
# HOSTS/GHOST/DEFAULT.NIX - Ghost Laptop Configuration
# ═══════════════════════════════════════════════════════════════════════════════
#
# Main entry point for the Ghost laptop host.
#
# ═══════════════════════════════════════════════════════════════════════════════

{ config, pkgs, lib, inputs, vars, const, mlib, ... }:

{
  imports = [
    # Hardware configuration (MANDATORY - generated by nixos-generate-config)
    # For disko installs, use a simplified hardware.nix that doesn't define filesystems
    ./hardware.nix
    
    # Disko configuration - uncommented for fresh installs with disko
    # This defines LUKS + BTRFS partitioning declaratively
    ./disko.nix
  ];
  
  # ═══════════════════════════════════════════════════════════════════════════
  # HOST METADATA
  # ═══════════════════════════════════════════════════════════════════════════
  networking.hostName = "ghost";
  system.stateVersion = "26.05";
  
  # ═══════════════════════════════════════════════════════════════════════════
  # BOOT CONFIGURATION
  # ═══════════════════════════════════════════════════════════════════════════
  # Systemd-boot (UEFI) - works with disko's ESP partition
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  
  # Kernel
  boot.kernelPackages = pkgs.linuxPackages_latest;
  
  # SSD optimizations
  boot.kernelParams = [
    "nohibernate"  # Disable hibernate for LUKS
    "elevator=none"  # Use MQ-BFQ scheduler
  ];
  
  # ═══════════════════════════════════════════════════════════════════════════
  # HOST-Specific PACKAGES
  # ═══════════════════════════════════════════════════════════════════════════
  environment.systemPackages = with pkgs; [
    # Laptop-specific tools
    powertop
    tlp
    acpi
    
    # ThinkPad-specific
    linux-firmware
  ];
  
  # ═══════════════════════════════════════════════════════════════════════════
  # LAPTOP OPTIMIZATIONS
  # ═══════════════════════════════════════════════════════════════════════════
  # Power management
  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
    };
  };
  
  # Disable power-profiles-daemon (conflicts with TLP)
  services.power-profiles-daemon.enable = lib.mkForce false;
  
  # Enable brightness control
  hardware.brillo.enable = true;
  
  # Enable touchpad support
  services.libinput.enable = true;
}