# ═══════════════════════════════════════════════════════════════════════════════
# HOSTS/GHOST/DEFAULT.NIX - Ghost Laptop Configuration
# ═══════════════════════════════════════════════════════════════════════════════
#
# Main entry point for the Ghost laptop host.
#
# ═══════════════════════════════════════════════════════════════════════════════

{ config, pkgs, lib, inputs, vars, const, mlib, ... }:

{
  imports = [
    # Hardware configuration (MANDATORY - generated by nixos-generate-config)
    ./hardware.nix
    
    # Disko configuration (optional - for fresh installs)
    # ./disko.nix
  ];
  
  # ═══════════════════════════════════════════════════════════════════════════
  # HOST METADATA
  # ═══════════════════════════════════════════════════════════════════════════
  networking.hostName = "ghost";
  system.stateVersion = "26.05";
  
  # ═══════════════════════════════════════════════════════════════════════════
  # BOOT CONFIGURATION
  # ═══════════════════════════════════════════════════════════════════════════
  boot.loader.grub.device = lib.mkForce "nodev";
  boot.kernelPackages = pkgs.linuxPackages_latest;
  
  # ═══════════════════════════════════════════════════════════════════════════
  # HOST-Specific PACKAGES
  # ═══════════════════════════════════════════════════════════════════════════
  environment.systemPackages = with pkgs; [
    # Laptop-specific tools
    powertop
    tlp
    acpi
    
    # ThinkPad-specific
    linux-firmware
  ];
  
  # ═══════════════════════════════════════════════════════════════════════════
  # LAPTOP OPTIMIZATIONS
  # ═══════════════════════════════════════════════════════════════════════════
  # Power management
  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
    };
  };
  
  # Enable brightness control
  hardware.brillo.enable = true;
  
  # Enable touchpad support
  services.xserver.libinput.enable = true;
}
