# ═══════════════════════════════════════════════════════════════════════════════
# HOSTS/GHOST/HARDWARE.NIX - Hardware Configuration
# ═══════════════════════════════════════════════════════════════════════════════
#
# This file was originally generated by nixos-generate-config.
# It contains hardware-specific settings that should NOT be manually edited.
#
# To regenerate:
#   sudo nixos-generate-config --no-filesystems --show-hardware-config > hosts/ghost/hardware.nix
#
# ═══════════════════════════════════════════════════════════════════════════════

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];
  
  # ═══════════════════════════════════════════════════════════════════════════
  # BOOT MODULES
  # ═══════════════════════════════════════════════════════════════════════════
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  
  # ═══════════════════════════════════════════════════════════════════════════
  # FILESYSTEMS
  # ═══════════════════════════════════════════════════════════════════════════
  # NOTE: These UUIDs are placeholders - update with actual values from your system
  # Use `lsblk -f` to find actual UUIDs
  #
  # boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/YOUR-UUID-HERE";
  
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/YOUR-ROOT-UUID";
    fsType = "ext4";
  };
  
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/YOUR-BOOT-UUID";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };
  
  # swapDevices = [ { device = "/dev/disk/by-uuid/YOUR-SWAP-UUID"; } ];
  
  # ═══════════════════════════════════════════════════════════════════════════
  # HARDWARE SETTINGS
  # ═══════════════════════════════════════════════════════════════════════════
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  
  # CPU microcode
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # Power management
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  
  # Video drivers
  services.xserver.videoDrivers = [ "modesetting" ];
  
  # OpenGL
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };
}
