# ═══════════════════════════════════════════════════════════════════════════════
# HOSTS/GHOST/HARDWARE.NIX - Hardware Configuration
# ═══════════════════════════════════════════════════════════════════════════════
#
# This file was originally generated by nixos-generate-config.
# It contains hardware-specific settings for the Ghost laptop (Lenovo ThinkPad P1 Gen 4).
#
# Generated from: /etc/nixos/hardware-configuration.nix
#
# ═══════════════════════════════════════════════════════════════════════════════

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ═══════════════════════════════════════════════════════════════════════════
  # BOOT MODULES
  # ═══════════════════════════════════════════════════════════════════════════
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"  # Thunderbolt support
    "vmd"          # Intel Volume Management Device
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];  # Intel virtualization
  boot.extraModulePackages = [ ];

  # ═══════════════════════════════════════════════════════════════════════════
  # LUKS ENCRYPTION - Optimized for SSD performance
  # ═══════════════════════════════════════════════════════════════════════════
  # Root filesystem is encrypted with LUKS
  boot.initrd.luks.devices."luks-73f977e2-cc74-43cb-9785-469f34254193" = {
    device = "/dev/disk/by-uuid/73f977e2-cc74-43cb-9785-469f34254193";
    # SSD optimizations for faster boot
    allowDiscards = true;      # Enable TRIM support for SSD performance
    bypassWorkqueues = true;     # Reduce latency on SSDs
  };
  
  # Swap encryption with same optimizations
  boot.initrd.luks.devices."luks-2489b697-27f0-4e66-bae0-c32a2078c9f5" = {
    device = "/dev/disk/by-uuid/2489b697-27f0-4e66-bae0-c32a2078c9f5";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # FILESYSTEMS
  # ═══════════════════════════════════════════════════════════════════════════
  fileSystems."/" = {
    device = "/dev/mapper/luks-73f977e2-cc74-43cb-9785-469f34254193";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3366-8701";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # SWAP - Using the decrypted LUKS device
  # ═══════════════════════════════════════════════════════════════════════════
  swapDevices = [
    { device = "/dev/mapper/luks-2489b697-27f0-4e66-bae0-c32a2078c9f5"; }
  ];

  # ═══════════════════════════════════════════════════════════════════════════
  # HARDWARE SETTINGS
  # ═══════════════════════════════════════════════════════════════════════════
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # CPU microcode updates
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Power management
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
